spring:
  application:
    name: petfriends-pedido

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:h2:mem:pedido-db
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

server:
  port: 8080
